AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  NewCops: disable

LineLength:
  Max: 120

Metrics:
  Enabled: false

Style:
  Enabled: false

Layout:
  Enabled: false

Bundler:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
